#!/bin/bash
#
# Copyright 2014-2015 Numenta Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Make sure all our parameters are set before we call burnrate_collect_data.py

validate_parameters(){
  ERRORS=""
  if [ -z ${GROK_SERVER} ]; then
    echo "You need to set GROK_SERVER!"
    ERRORS=1
  fi
  if [ -z ${GROK_API_KEY} ]; then
    echo "You need to set GROK_API_KEY!"
    ERRORS=1
  fi
  if [ -z ${AWS_ACCESS_KEY_ID} ]; then
    echo "You need to set AWS_ACCESS_KEY_ID!"
    ERRORS=1
  fi
  if [ -z ${AWS_SECRET_ACCESS_KEY} ]; then
    echo "You need to set AWS_SECRET_ACCESS_KEY!"
    ERRORS=1
  fi

  if [ ! -z "${ERRORS}" ]; then
    exit 1
  fi
}

validate_parameters

touch /metrics/burn.csv

/usr/local/bin/burnrate_collect_data -brpt \
  -s ${GROK_SERVER} \
  -k ${GROK_API_KEY} \
  --verbose \
  -o /metrics/burn.csv $@
